"""
RA-MARS AI Model Training Script

This script trains multiple machine-learning models on the synthetic UAV mission
dataset generated by generate_dataset.py.

Output:
- simulations/results/model_performance.csv
"""

import os
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import LinearSVC


DATA_PATH = "simulations/datasets/synthetic_uav_mission_data.csv"
OUTPUT_DIR = "simulations/results"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "model_performance.csv")


FEATURES = [
    "packet_loss_rate",
    "latency_ms",
    "route_deviation",
    "gps_jump",
    "velocity_inconsistency",
    "battery_level",
    "mission_progress",
    "log_integrity_status",
    "tamper_flag",
    "risk_score",
]


def load_data(sample_size=120000):
    if not os.path.exists(DATA_PATH):
        raise FileNotFoundError(
            f"Dataset not found: {DATA_PATH}. Run generate_dataset.py first."
        )

    df = pd.read_csv(DATA_PATH)

    if len(df) > sample_size:
        df = df.sample(n=sample_size, random_state=42)

    X = df[FEATURES]
    y = df["label"]

    return train_test_split(
        X,
        y,
        test_size=0.25,
        random_state=42,
        stratify=y,
    )


def evaluate_model(name, model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    predictions = model.predict(X_test)

    return {
        "model": name,
        "accuracy": accuracy_score(y_test, predictions),
        "precision_macro": precision_score(y_test, predictions, average="macro", zero_division=0),
        "recall_macro": recall_score(y_test, predictions, average="macro", zero_division=0),
        "f1_macro": f1_score(y_test, predictions, average="macro", zero_division=0),
    }


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)

    X_train, X_test, y_train, y_test = load_data()

    models = [
        (
            "Logistic Regression",
            Pipeline(
                [
                    ("scaler", StandardScaler()),
                    ("model", LogisticRegression(max_iter=1000, n_jobs=-1)),
                ]
            ),
        ),
        (
            "Linear SVM",
            Pipeline(
                [
                    ("scaler", StandardScaler()),
                    ("model", LinearSVC(max_iter=5000)),
                ]
            ),
        ),
        (
            "Random Forest",
            RandomForestClassifier(
                n_estimators=120,
                random_state=42,
                n_jobs=-1,
                max_depth=14,
            ),
        ),
        (
            "Gradient Boosting",
            GradientBoostingClassifier(random_state=42),
        ),
    ]

    results = []

    for name, model in models:
        print(f"Training {name}...")
        result = evaluate_model(name, model, X_train, X_test, y_train, y_test)
        results.append(result)
        print(result)

    results_df = pd.DataFrame(results)
    results_df.to_csv(OUTPUT_PATH, index=False)

    print(f"Saved model performance results to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
